### ISSUE TITLE
lookup transform from m_base_frame to m_odom_frame with scan stamp randomly failing

### ISSUE THREAD

**Issue by Jerzus** [neobotix/neo_localization2#29]
Neo localization is randomly failing, because of old transformation data.  Sometimes it is only 10 ms, sometimes more. 
Examle log:
[WARN] [1690986926.240108936]: NeoLocalizationNode: lookupTransform(m_base_frame, m_odom_frame) failed:  
Lookup would require extrapolation into the future. Requested time 1690986926.212936 but the latest data is at time 1690986926.200893, when looking up transform from frame [base_link] to frame [odom]

I am using Ros2 Iron, tested with different DDS's , even attempted to write own subscription of topic /tf. 

I've checked with ros2 topic hz, and ros2 topic echo if there are other issues with publishing on /tf transformation from odom to base. There are no issues, stable 30 Hz.  I know that latest data times from log aren't the same as time stamps of transformation  from odom to base. Maybe there is problem. 

Thanks for help!

Transformations from odom to base are identical on /tf and /odom:
![image](https://github.com/neobotix/neo_localization2/assets/73592748/e3af4888-9baf-4052-8cc8-112fb0b16d07)
![image](https://github.com/neobotix/neo_localization2/assets/73592748/a3ebb124-483b-48fd-afc5-976c0ebefbc8)

**Comment by padhupradheep** [comment]
Thanks for reporting the issue. 

Before starting to debug, could you please tell me your complete setup? Like the robot, lasers that you use and what frequency does your laser scanner publish data and anything else related..

**Comment by Jerzus** [comment]
Thanks for answer.

It is custom, differential robot with 2x SICK nanoScan3 publishing at 30 Hz. I am publishing to /scan with 30 Hz after merging them. I will give more details tomorrow, if there will be any difference without custom merging laser scanners.

**Comment by padhupradheep** [comment]
Could you also please share the parameters that you use?

**Comment by Jerzus** [comment]
update_gain: 0.4
    confidence_gain: 0.01
    sample_rate: 10
    loc_update_rate: 20
    map_update_rate: 0.5
    map_size: 1000
    map_downscale: 0
    num_smooth: 5
    min_score: 0.2
    odometry_std_xy: 0.01
    odometry_std_yaw: 0.01
    min_sample_std_xy: 0.025
    min_sample_std_yaw: 0.025
    max_sample_std_xy: 0.5
    max_sample_std_yaw: 0.5
    constrain_threshold: 0.1
    constrain_threshold_yaw: 0.2
    min_points: 20
    solver_gain: 0.1
    solver_damping: 1000.0
    solver_iterations: 10
    transform_timeout: 1.5
    broadcast_tf: true

**Comment by Jerzus** [comment]
file:///home/jerzus/Downloads/untitled.png

**Comment by Jerzus** [comment]
![untitled](https://github.com/neobotix/neo_localization2/assets/73592748/b47eb94a-13e7-444d-a122-a4eaaad46a2a)

**Comment by padhupradheep** [comment]
Seems to be some sort of race condition

Before that, I think you are using the parameters from our test setup. I just realized that we didn't update those parameters (for example `loc_update_rate` was changed to `loc_update_time` and so on..) since 2 years and the documentation too. Could you try adapting the [neo_mp_400](https://github.com/neobotix/neo_mp_400-2/blob/rolling/configs/navigation/navigation.yaml) parameter for your robot and see if this condition gets resolved?

We'll update the documentation and as well as the test launch. Btw, thanks for reporting the issue.

**Comment by Jerzus** [comment]
Changed parameters are loc_update_time, solver_iterations (from 10 to 20) and transform_timeout (from 1.5 to 0.2) and almost nothing changed. These parameters have small impact to frequency of errors. Everage rate of /tf map to odom is faster.

**Comment by padhupradheep** [comment]
> Everage rate of /tf map to odom is faster.

What's the rate of that now?

**Comment by Jerzus** [comment]
/tf map to odom rate ( using lookupTransform, without my subscribtion ) it was 4.4 before
![image](https://github.com/neobotix/neo_localization2/assets/73592748/1f3ee590-3660-4601-b5ac-393f97a76637)

**Comment by Jerzus** [comment]
I found that parameter **m_transform_timeout** isn't used in neo_localization_node.cpp. So there is unused variable and unnecessary parameter in config.

**Comment by Jerzus** [comment]
These are timestamps of laser scan and odom transform when `buffer->lookupTransform(m_odom_frame, m_base_frame, tf2::TimePointZero)` is used insted of `buffer->lookupTransform(m_odom_frame, m_base_frame, scan->header.stamp)`. When the proper ( second ) version is used time stamps are equal.

![image](https://github.com/neobotix/neo_localization2/assets/73592748/96602e37-ddb4-4303-a6d9-7112f01b3d54)

**Comment by Jerzus** [comment]
I can give you more details if you would like to know some specific.

**Comment by padhupradheep** [comment]
Did you try using just the single laser scanner instead of the combined scanners? 

I feel since the rate of your odom data is lesser than the combined laser scanner data, then this issue could occur.

**Comment by Jerzus** [comment]
> Did you try using just the single laser scanner instead of the combined scanners?
> 
> I feel since the rate of your odom data is lesser than the combined laser scanner data, then this issue could occur.

Yes, I have tried that.

**Comment by padhupradheep** [comment]
Okay, let me reproduce the issue in the simulation and get back to you soon. 

On our robots, we don't have any problems

**Comment by Jerzus** [comment]
Everage rate is 4.8 when using navigation.

**Comment by padhupradheep** [comment]
I was able to reproduce the issue. I set the publishing rate of odom to 30 Hz and the scanner to 40 Hz. As said before, the warning is expected and caused because of the race condition. 

neo_localization expects the odom data to be must faster than the laser scanner data. Also, the odom data is used explicitly in the pose estimation. 

Therefore, please make sure that your odom data is faster than the laser scanner data for the obvious reason.

> Everage rate is 4.8 when using navigation.

The slower rate is because of the above mentioned race condition. 

Feel free to continue in the thread if you have any questions.

**Comment by Jerzus** [comment]
I've set rate of odom to 60 Hz (stability of odom is fine). Scanner is 34 Hz. After that neo works fine with 5.6 Hz and deviation 0.014 s. There are lookupTransform issues for a few seconds after turning all ros processes on, but it is fine.

Does 100% load of one core could cause instability of localization in the future?

I have question on how low `loc_update_time` parameter should be to avoid any problems.

Also I would like to know at what ranges can I tweak these parameters.
![image](https://github.com/neobotix/neo_localization2/assets/73592748/86d37191-d485-4311-aeb5-b9cd2c4a748d)

I would be grateful to you for answering my questions.
Thanks for help!

**Comment by padhupradheep** [comment]
> After that neo works fine with 5.6 Hz

That is bit odd. if you had set the `loc_update_time` to 100ms then the `amcl_pose` should be already be published at 10 Hz. 

Theoretically speaking a single SICK laser scanner publishes data at 12 Hz, therefore the `loc_update_time` can be as close as to the 12 Hz. I'm not sure which laserscanners you are using, but the `loc_update_time` should not exceed `loc_update_time`. 

But since you also say that one of the core already reaches 100 %, I think that could be a possible issue. 

Can you tell me the specification of your computer? The least that we tested this computer was an i3 computer but 4 cores with good RAM and clock speed in terms of industrial standards and were able to achieve localization at 10 Hz. 

We can look into the rest of questions later, once this is out of the way.

**Comment by Jerzus** [comment]
I am using SICK laser scanner which publishes data at 34 Hz. `loc_update_time` is 100. Without merging scans I achieved 7.5 Hz.

![image](https://github.com/neobotix/neo_localization2/assets/73592748/d2ecdfad-33d2-4361-8b94-6f5e818a8ebb)

I use intel i3 12100 ( 4 cores, 8 threads, 4.1 GHz ) and 8 GB of DDR 4 RAM ( 3200 MHz, cl16 ??? ). 

Neo localization uses from 120% to 180% of core. I am wasting a bit of CPU with scans merging ( I will fix it ), but it should not influence 100% core load since it is separate node and average CPU load is 50% in the worst case scenario.

**Comment by Jerzus** [comment]
I have update: 
`loc_update_time` is set to 100 ms.
Odom is published at 70 Hz.
Scan is published at 34 Hz. 
Neo is publishing at 8 Hz. 
Utilization of CPU is fine, neo_localization stopped using 100% of core.

Lookup transform error still comes up, but not so often. Everything is working fine but console logs are thought-provoking. I haven't changed config parameters since last discussion.

What could be the cause? Thanks for answer.
