### ISSUE TITLE
How to make the navigation stack work for Foxy

### ISSUE THREAD

**Issue by RemiFabre** [neobotix/neo_localization2#6]
The documentation (https://docs.neobotix.de/display/R2/Installation+on+Ubuntu) says the stack is compatible with Foxy, but the Foxy branch of this repo is empty and the other branches do not compile.
Any tips ?

**Comment by padhupradheep** [comment]
Hello Remi, Thanks for pointing it out. Unfortunately, we do not support Foxy distro for ROS-2, since the packages surrounding it are much better in Galactic. But, if you need it for any specific use-case, we will try to extend it for foxy as well. 

It would be easier for us to do the back porting, if you can send me the details of your compilation errors.

**Comment by RemiFabre** [comment]
Thank you for your fast reply and offering to back port. 

To clarify my message, I meant "the others branches of this repo do not compile on a Foxy workspace" (as in I was hoping I could backport the Galaxy branch).

However the navigation stack does work with Foxy, since neo_localization2 is not used (e.g. I'm able to `ros2 launch neo_simulation2 navigation.launch.py`). This is enough for me as of now.

Thanks again, closing the ticket

**Comment by padhupradheep** [comment]
>  I meant "the others branches of this repo do not compile on a Foxy workspace" 

Of course other branches does not compile with the Foxy branch because of the API changes that were involved in Galactic or rolling. 

> However the navigation stack does work with Foxy, since neo_localization2 is not used (e.g. I'm able to ros2 launch neo_simulation2 navigation.launch.py). This is enough for me as of now.

Glad you found the solution.
